### ISSUE TITLE
Full Stack IOS engineering job at fast paced startup

### ISSUE THREAD

**Issue by SwaminathaSwami** [jessesquires/esoteric-swift#6]
Greetings Contributors of esosteric-swift,

I'm the CEO of Scope. I came across your profile and saw you attended make school, and it reminded me that we are actively hiring for talented engineers. I wanted to see if you'd be interested in working with us at Scope— if you're up for it, I'd love to have a phone call next week to chat. 

- Pranav Neyveli

**Comment by jessesquires** [comment]
@hcpsneyvelip 

![](https://media.giphy.com/media/XozypzpGakVuX2ciZJ/giphy.gif)
